### ISSUE TITLE
gaming value

### ISSUE THREAD

**Issue by hegelsu** [blacksourcez/Warcraft-StateCheck#2]
Dim adr As Integer = (_Memory.GetBaseAddress("Game.dll") + &HACE638)
 Dim value As Integer = _Memory.ReadInteger(adr)
I find this value is 414 not 404 when gaming, why?

**Comment by hegelsu** [comment]
I know:
414: 1.20--1.28.1
404: 1.28.2--1.28.5
537: 1.29

I can't find value for 1.30+

**Comment by ayuthmang** [comment]
I didn't play wc3 for 7 years. Every patch of wc3 you need to find new address every single patch. 

How to find it? 
Restore patch to 1.26a and use hex editor and goto address ACE638 and seclect the pattern of address then go to latest patch and find the same pattern.

Feel free to open issue and pull request.

If you have any questions please don't hesitate to ask me.
